name: Run Python script daily

on:
  schedule:
    - cron: '0 0 * * *'  # Todos los días a medianoche UTC
  workflow_dispatch:     # Permite ejecutarlo manualmente también

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Export secrets
        run: |
          echo "NOTION_SECRET=${{ secrets.NOTION_SECRET }}" >> $GITHUB_ENV
          echo "DATABASE_ID=${{ secrets.DATABASE_ID }}" >> $GITHUB_ENV
          echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> $GITHUB_ENV
          echo "CHAT_ID=${{ secrets.CHAT_ID }}" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_ASSOCIATE_TAG=${{ secrets.AWS_ASSOCIATE_TAG }}" >> $GITHUB_ENV

      - name: Run script
        run: python main.py
