name: Run Python script daily

on:
  schedule:
    - cron: '0 0 * * *'  # Todos los días a medianoche UTC
  workflow_dispatch:     # Permite ejecutarlo manualmente también

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script with secrets
        env:
          NOTION_SECRET: ${{ secrets.NOTION_SECRET }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ASSOCIATE_TAG: ${{ secrets.AWS_ASSOCIATE_TAG }}
        run: python main.py
